### ISSUE TITLE
news page

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/funding-conference-2016#3]
I wrecked the News page and can't seem to get my post to work. all the text is there I just can seem make all of it be seen, maybe because there is an error.

**Comment by Hoverbear** [comment]
I wasn't sure what text you were referring to, but perhaps that helps.

**Comment by Hoverbear** [comment]
Is there any particular reason you're bunching all of your posts into a single document instead of having multiple files? I can tidy it up if you're just confused about how it works. :)

**Comment by DellaPreston** [comment]
AH: Is there any particular reason you're bunching all of your posts into a single document instead of having multiple files?
DP: no reason. 

 AH: I can tidy it up if you're just confused about how it works. :)
DP: I don't thin we know how it work, if you could tidy it up that would be great

**Comment by Hoverbear** [comment]
https://github.com/BCAAFC/funding-conference-2016/commit/6c9f654ee64cf298dde1a17aea1f2f47aa12fd0b split up the posts into multiple pages.

You can see https://github.com/BCAAFC/funding-conference-2016/tree/master/_posts how it's laid out.

This may work better for you. :)
