### ISSUE TITLE
new post attempt

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/funding-conference-2016#4]
Hi Andrew I tried to make a new post with no success. 

how do I make a new post?

There is one sitting in the posts name Proposal Writing

it won't go live. I think I need those little arrows that point down where the dashes are ---  but i don't know how to do that. I searched our markdown cheat sheet but could not find out how.

**Comment by Hoverbear** [comment]
So close! You forgot the dash in the name between the date and the title, quite understandable. :)

`1990-04-23-andrew-is-born.md` is the correct format, where you had `1990-04-23andrew-is-born.md`
