### ISSUE TITLE
resources page

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/funding-conference-2016#6]
Request to build a resources page. I envision this page the the ability to post ppt, pdf, word docs.

Eg: it would look like:

Name the Funding
Name Who Provides Funding
Website Link
Download Application (this is where I can add the Doc, ppt, pdf)

Name the Funding
Name Who Provides Funding
Website Link
Download Application (this is where I can add the Doc)

Name the Funding
Name Who Provides Funding
Website Link
Download Application (this is where I can add the Doc)

etc.....

**Comment by Hoverbear** [comment]
Please see `resources.md` and the `public/resources/` folder. :)

Right now the examples are bordered by `<!--` and `-->` which hides them, you can remove them and they'll start showing.
