### ISSUE TITLE
resources 2015 button

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/funding-conference-2016#7]
on the resources page 
can we have buttons for: (redirected to it own page)
2015 conference resources
2016 conference resources
other resources

we want to keep the same layout for each page

**Comment by Hoverbear** [comment]
Yup!

![space](https://cloud.githubusercontent.com/assets/130903/19837356/b82f06c8-9eb8-11e6-803d-c2c82dce0864.gif)
